### PR TITLE
Address latest comments in PR

### PR DESCRIPTION
**Pull request by rishabh246**
##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by rishabh246** [comment]
I only ran make test. Let me know if I should run something else too

**Comment by ntauth** [comment]
> I only ran make test. Let me know if I should run something else too

`make test` is enough, and a `make update` should also be performed after adding new documentation (*.pod) files.

**Comment by ntauth** [comment]
> ##### Checklist
> * [ ]  documentation is added or updated
> * [ ]  tests are added or updated

What tests are you referring to here?

**Comment by rishabh246** [comment]
> > ##### Checklist
> > 
> > * [ ]   documentation is added or updated
> > * [ ]   tests are added or updated
> 
> What tests are you referring to here?

This is weird. I don't remember adding this comment at all

**Comment by rishabh246** [comment]
Not sure what to do. My changes are trivial

**Comment by ntauth** [comment]
The fuzzing check is still failing for the same reason, completely unrelated to the changes.

**Pull request merged**
